// Package adapters are the glue between components and external sources.
// # This manifest was generated by ymir. DO NOT EDIT.
package adapters

import (
	"fmt"
	"net"
	"strconv"
	"time"

	// mysql go lib.
	"github.com/go-sql-driver/mysql"

	"entgo.io/ent/dialect"
	sqlEnt "entgo.io/ent/dialect/sql"
	"github.com/rs/zerolog/log"
)

var YmirblogMySQLOpen = sqlEnt.Open // YmirblogMySQLOpen will invoke to test case.

// YmirblogMySQL is data of instances.
type YmirblogMySQL struct {
	NetworkDB
	driver *sqlEnt.Driver
}

// Open is open the connection of mysql.
func (y *YmirblogMySQL) Open() (*sqlEnt.Driver, error) {
	if y.driver == nil {
		return nil, fmt.Errorf("driver was failed to connected")
	}
	return y.driver, nil
}

// Connect is connected the connection of YmirblogMySQL.
func (y *YmirblogMySQL) Connect() (err error) {
	y.driver, err = YmirblogMySQLOpen(dialect.MySQL, y.dsn())
	if err != nil {
		log.Error().Err(err).Msg("YmirblogMySQLOpen is failed to open")
		return err
	}

	if y.MaxIdleCons == 0 {
		y.driver.DB().SetMaxIdleConns(0)
	} else {
		y.driver.DB().SetMaxIdleConns(y.MaxIdleCons)
	}
	return nil
}

// Disconnect is disconnect the connection of YmirblogMySQL.
func (y *YmirblogMySQL) Disconnect() error {
	return y.driver.Close()
}

func (y *YmirblogMySQL) dsn() string {
	cfg := mysql.Config{
		User:                 y.User,
		Passwd:               y.Password,
		DBName:               y.Database,
		Timeout:              time.Second * time.Duration(y.ConnectionTimeout),
		ParseTime:            true,
		AllowNativePasswords: true,
		Params:               make(map[string]string),
	}
	if y.Host != "" {
		if y.Host[0] != '/' {
			cfg.Net = "tcp"
			cfg.Addr = y.Host

			if y.Port != 0 {
				cfg.Addr = net.JoinHostPort(y.Host, strconv.Itoa(int(y.Port)))
			}
		} else {
			cfg.Net = "unix"
			cfg.Addr = y.Host
		}
	}
	return cfg.FormatDSN()
}

// WithYmirblogMySQL option function to assign on adapters.
func WithYmirblogMySQL(driver Driver[*sqlEnt.Driver]) Option {
	return func(a *Adapter) {
		if err := driver.Connect(); err != nil {
			panic(err)
		}
		open, err := driver.Open()
		if err != nil {
			panic(err)
		}
		a.YmirblogMySQL = open
	}
}
